name: PreCICE CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: '0 0 * * 0'

jobs:
  build:
    name: Build ${{ matrix.build_type }}-dealii:${{ matrix.dealii_version }}-${{ matrix.ubuntu_version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: ["Debug"]
        dealii_version: ["master", "v9.4.0"]
        ubuntu_version: ["jammy"]

    container:
      image: dealii/dealii:${{ matrix.dealii_version }}-${{ matrix.ubuntu_version }}
      options: --user root

    steps:
      - name: Install preCICE
        run: |
          sudo apt-get -y update
          wget https://github.com/precice/precice/releases/download/v2.5.0/libprecice2_2.5.0_${{ matrix.ubuntu_version }}.deb
          sudo apt-get -y install ./libprecice2_2.5.0_${{ matrix.ubuntu_version }}.deb

      - uses: actions/checkout@v3

      - name: Compile
        run: |
          cd coupled_laplace_problem
          cmake .
          make

      - name: Test
        run: |
          cd coupled_laplace_problem
          (./coupled_laplace_problem 2>&1 & ./fancy_boundary_condition >fbc.log)
          sed -i '2d' solution-10.vtk
          numdiff solution-10.vtk test_data/reference-10.vtk
