name: PreCICE CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron:  '0 0 * * 0'

jobs:
  build:
    name: Build ${{ matrix.build_type }}-dealii:${{ matrix.dealii_version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: ["Debug"]
        dealii_version: ["master", "v9.4.0"]

    container:
      image: dealii/dealii:${{ matrix.dealii_version }}-focal

    steps:
      - name: Setup
        run: |
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE
          
      - uses: actions/checkout@v2

      - name: Compile
        run: |
          sudo apt-get -y update
          wget https://github.com/precice/precice/releases/download/v2.3.0/libprecice2_2.3.0_focal.deb
          sudo apt-get -y install ./libprecice2_2.3.0_focal.deb
          cd coupled_laplace_problem
          cmake .
          make

      - name: Test
        run: |
          cd coupled_laplace_problem
          (./coupled_laplace_problem 2>&1 & ./fancy_boundary_condition >fbc.log)
          sed -i '2d' solution-10.vtk
          numdiff solution-10.vtk test_data/reference-10.vtk
