name: PreCICE CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: |
         command="sudo apt-get -y update && \
                  wget https://github.com/precice/precice/releases/download/v2.1.1/libprecice2_2.1.1_focal.deb && \
                  sudo apt-get -y install ./libprecice2_2.1.1_focal.deb && \
                  git clone https://github.com/${{ github.repository }} && \
                  cd code-gallery && \
                  git fetch origin ${{ github.ref }} && \
                  git checkout FETCH_HEAD && \
                  cd coupled_laplace_problem && \
                  cmake . && \
                  make && \
                  (./coupled_laplace_problem 2>&1 & ./fancy_boundary_condition >fbc.log) && \
                  sed -i '2d' solution-10.vtk && \
                  numdiff solution-10.vtk test_data/reference-10.vtk";
         
         echo $command
         
         docker pull dealii/dealii:v9.4.0-focal
         docker run -t dealii/dealii:v9.4.0-focal /bin/sh -c "$command";
